site_name: Ray's Personal Website

theme:
  name: material
  logo: assets/Chess_qlt45.svg
  favicon: assets/Chess_qlt45.svg

# 左側的導覽列選單
nav:
  - Home Page: index.md
  - About: about.md
  - Studies: studies.md
  - Notes: notes.md
  - Experiences & Advice: experiences_advice.md
  - Culture Log: culture_log.md


plugins:

# 啟用 LaTeX 數學公式渲染與相關擴充功能
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
